# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=20, verbose_name='Customer Firstname')),
                ('Lastname', models.CharField(max_length=20, verbose_name='Customer Lastname')),
                ('Location', models.CharField(max_length=20, verbose_name='Customer Location')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.IntegerField(max_length=4)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, verbose_name='Product Name')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product Price')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.Product'),
        ),
    ]
