# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Qty',
            field=models.IntegerField(),
        ),
    ]
