# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0002_auto_20161206_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Product Price'),
        ),
    ]
