# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0003_auto_20161206_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Total',
        ),
    ]
